# Generated by Django 3.1.4 on 2020-12-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('Category_name', models.CharField(max_length=248, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('Phone_number', models.IntegerField(primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=50)),
                ('Last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('billing_address', models.CharField(max_length=248)),
                ('Shipping_address', models.CharField(max_length=248)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=100)),
                ('Product_image', models.ImageField(upload_to='')),
                ('Price', models.IntegerField()),
                ('discount_price', models.IntegerField(null=True)),
                ('Quantity', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
