# Generated by Django 3.1.4 on 2021-01-06 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210104_1528'),
    ]

    operations = [
    ]
