# Generated by Django 3.1.4 on 2021-01-06 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210106_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
